# Generated by Django 4.2.17 on 2024-12-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField(null=True)),
                ('OrderStatus', models.CharField(choices=[('in_progress', 'В процессе'), ('packed', 'Собран'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=255)),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderCosts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItems', to='Orders.orders')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.products')),
            ],
        ),
    ]
