# Generated by Django 4.2.17 on 2024-12-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_costs_alter_products_image'),
        ('Orders', '0002_remove_orders_user_orders_customer_orders_duedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Products',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItems', to='Orders.orders')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.products')),
            ],
        ),
    ]
