# Generated by Django 4.2.17 on 2024-12-29 12:35

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(default='')),
                ('Image', models.ImageField(upload_to=Products.models.Products.upload_product)),
                ('InStock', models.IntegerField(default=0)),
            ],
        ),
    ]
