# Generated by Django 4.2.17 on 2024-12-25 10:23

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Costs',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to=Products.models.Products.upload_product),
        ),
    ]
