# Generated by Django 4.2.17 on 2024-12-29 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 29, 16, 14, 43, 294370)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
