# Generated by Django 4.2.17 on 2024-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
